### ISSUE TITLE
API keys or username/password?

### ISSUE THREAD

**Issue by mtrogers** [mongodb/atlas-billing#11]
Fixed. Seems like the dashboard import didn't properly access "billing.details" for some reason. Rerunning the charts a couple of times seems to have done the trick.

My charts are all red, as it seems they don't have access to the collections.
![image](https://user-images.githubusercontent.com/6350109/199586412-cb76a1a0-bd97-490d-a8c9-f729e2984baf.png)
Calling the realm-cli function run:

```
... atlas-billing % realm-cli function run
? Select Function getdata_latest
Result
{
  "org": {
    "$undefined": true
  },
  "status": [
    "FunctionError: http request: \"username\" argument must be a string",
    "FunctionError: http request: \"username\" argument must be a string",
    "FunctionError: http request: \"username\" argument must be a string"
  ]
}

```
realm-cli returns the setup secrets from the script..
The application seems to be using a username/password based function set. 
```
exports = async function(org, username, password){

  const promises = [
    getInvoices(org, username, password),
    getOrg(org, username, password),
    getProjects(org, username, password)
  ];
```

I followed the instructions extensively, but it seems like they may be a bit out of date. Any idea what I'm doing wrong?

**Comment by michaelsew** [comment]
FYI, I ran into the same issue. Re-importing the chart would not help.  I ended up clicking on each individual widget -> Edit, then select the datasource manually via drop-downs.  Oddly, it worked after that.
